CREATE TABLE SEMINAR ( 
SeminarID int NOT NULL,
SeminarDate datetime NOT NULL,
Location char(100) NOT NULL,
SeminarTitle char(100) NOT NULL
CONSTRAINT SEMIAR_PK PRIMARY KEY (SEMINARID)
); 

CREATE TABLE ZIP_CITY ( 
Zip int NOT NULL,
City char(100) NOT NULL
CONSTRAINT ZIP_CITY_PK PRIMARY KEY (Zip)
); 
CREATE TABLE CUSTOMER (
CustomerID int NOT NULL,
FirstName char (100) NOT NULL,
LastName char (100) NOT NULL,
Street char(100) NOT NULL,
Zip int NOT NULL
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CustomerID)
CONSTRAINT CUSTOMER_ZIP_FK FOREIGN KEY (Zip)
						   REFERENCES ZIP_CITY (Zip)
);

CREATE TABLE SEMINAR_CUSTOMER (
SeminarID int NOT NULL,
CustomerID int NOT NULL,
CONSTRAINT SEMINAR_CUSTOMER_PK PRIMARY KEY (SeminarID, CustomerID),
CONSTRAINT SEMINAR_CUSTOMER_SEMINARID FOREIGN KEY (SeminarID)
									  REFERENCES SEMINAR (SeminarID),
CONSTRAINT SEMINAR_CUSTOMER_CUSTOMERID FOREIGN KEY (CustomerID) 
									   REFERENCES CUSTOMER (CustomerID) 
);